ci: gocovmerge install
Signed-off-by: Ivan Velasco <ivan.velasco@socotra.com>

diff --git a/.github/workflows/feature-branch.yml b/.github/workflows/feature-branch.yml
--- a/.github/workflows/feature-branch.yml
+++ b/.github/workflows/feature-branch.yml
@@ -23,21 +23,24 @@ jobs:
       - name: Add Go Bin to PATH
         run: echo "$HOME/go/bin" >> $GITHUB_PATH
 
-      - name: Install Dependencies
-        run: go mod download
-
       - name: Install gocovmerge
         run: |
           go install github.com/wadey/gocovmerge@latest
-          echo "$HOME/go/bin" >> $GITHUB_PATH  # Add Go bin to PATH
+          echo "$HOME/go/bin" >> $GITHUB_PATH 
+
+      - name: Debug PATH and List Go Bin
+        run: |
+          echo "Current PATH: $PATH"
+          echo "Listing $HOME/go/bin:"
+          ls -la $HOME/go/bin
 
       - name: Verify gocovmerge Installation
         run: |
-          which gocovmerge
-          gocovmerge --version || echo "gocovmerge version not available"
-
-      - name: Install Dependencies
-        run: go mod download
+          if ! command -v gocovmerge &> /dev/null; then
+            echo "gocovmerge could not be found"
+            exit 1
+          fi
+          echo "gocovmerge is installed at $(which gocovmerge)"
 
       - name: Build using Makefile
         run: make build OS=linux ARCH=amd64
